import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";

import { env } from "~/env";
import { sendActionEmail } from "~/lib/email";
import { db } from "~/server/db";
import { user as userTable } from "~/server/db/schema";

export const auth = betterAuth({
  baseURL: env.BETTER_AUTH_URL,
  database: drizzleAdapter(db, {
    provider: "mysql", // SingleStore speaks the MySQL wire protocol
  }),
  user: {
    additionalFields: {
      // Declare the custom `role` column so better-auth persists it (the core
      // adapter only writes fields it knows about) and includes it in session
      // and user output. `input: false` prevents clients from setting it - the
      // role is assigned server-side only (first-user bootstrap below).
      role: {
        type: "string",
        required: false,
        defaultValue: "user",
        input: false,
      },
    },
  },
  emailAndPassword: {
    enabled: true,
    // Server-side floor for all password creation/changes. The full policy
    // (uppercase + number + symbol) is validated client-side, and this version
    // of better-auth only supports minPasswordLength here.
    minPasswordLength: 12,
    // Reset links are one-time and expire after 1 hour (better-auth default).
    resetPasswordTokenExpiresIn: 3600,
    // Security: resetting the password signs out every existing session,
    // including any a hijacker may hold.
    revokeSessionsOnPasswordReset: true,
    // Emails go through the same helper as verification (Resend; dev
    // console-log fallback). Reset links are generated by better-auth
    // (one-time, 1h expiry) and /api/auth/reset-password is already mounted.
    sendResetPassword: async ({ user, url }) => {
      await sendActionEmail({
        to: user.email,
        subject: "Reset your password",
        heading: "Reset your password",
        body: "We received a request to reset your password. Click the button below to choose a new one.",
        ctaLabel: "Reset password",
        ctaUrl: url,
      });
    },
  },
  emailVerification: {
    // Sign-ins stay open for unverified accounts by default. To require
    // verification before signing in, uncomment the next line:
    // requireEmailVerification: true,
    // Emails are sent through src/lib/email.ts (Resend). With no
    // RESEND_API_KEY the link is logged to the dev console instead - local
    // flows stay testable with zero setup. Verification links are generated
    // by better-auth (one-time, 1h expiry) and /api/auth/verify-email is
    // already mounted.
    sendVerificationEmail: async ({ user, url }) => {
      await sendActionEmail({
        to: user.email,
        subject: "Confirm your email",
        heading: "Confirm your email",
        body: "You recently created an account. Confirm your email address to finish setting it up.",
        ctaLabel: "Verify email",
        ctaUrl: url,
      });
    },
  },
  socialProviders: {
    github: {
      clientId: env.BETTER_AUTH_GITHUB_CLIENT_ID,
      clientSecret: env.BETTER_AUTH_GITHUB_CLIENT_SECRET,
      redirectURI: "http://localhost:3000/api/auth/callback/github",
    },
  },
  databaseHooks: {
    user: {
      create: {
        // The first user ever registered becomes the admin (bootstrap owner).
        before: async (user) => {
          const count = await db.$count(userTable);
          if (count === 0) {
            return { data: { ...user, role: "admin" } };
          }
        },
      },
    },
  },
});

export type Session = typeof auth.$Infer.Session;
